document.write("<div class=\"menu\"></div>")
document.write("<header><nav><ul>")
document.write("<li><a href=\"mathstat.html\">MATHSTAT</a><ul>")
document.write("</ul></li>")
document.write("<li><a href=\"cpp.html\">CPP</a><ul>")
document.write("</ul></li>")
document.write("<li><a href=\"csharp.html\">CSHARP</a><ul>")
document.write("</ul></li>")
document.write("</ul></nav></header>")
document.write("<script id=\"MathJax-script\" async src=\"https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js\"></script>")