document.write('<div class="menu"></div>')
document.write('<header><nav><ul>')
document.write('<li><a href="#">ТЕРВЕР | МАТСТАТ</a><ul>')
document.write('<li><a href="probtheory_1.html">1 ЭЛЕМЕНТЫ КОМБИНАТОРИКИ</a></li>')
document.write('<li><a href="probtheory_2.html">2 ОСНОВНЫЕ ПОНЯТИЯ ТЕРВЕР</a></li>')
document.write('<li><a href="probtheory_3.html">3 ВЕРОЯТНОСТЬ СОБЫТИЯ</a></li>')
document.write('<li><a href="probtheory_4.html">4 АКСИОМЫ ТЕОРЕМЫ ТЕРВЕР</a></li>')
document.write('<li><a href="probtheory_5.html">5 ПОЛНАЯ ВЕРОЯТНОСТЬ. БАЙЕС</a></li>')
document.write('<li><a href="probtheory_6.html">6 ПОВТОРНЫЕ ИСПЫТАНИЯ</a></li>')
document.write('<li><a href="probtheory_7.html">7 СЛУЧАЙНЫЕ ВЕЛИЧИНЫ</a></li>')
document.write('<li><a href="probtheory_8.html">8 ЧИСЛОВЫЕ ХАРАКТЕРИСТИКИ СВ</a></li>')
document.write('<li><a href="probtheory_9.html">9 ВАЖНЕЙШИЕ РАСПРЕДЕЛЕНИЯ СВ</a></li>')
document.write('<li><a href="mathstat_1.html">10 ЭЛЕМЕНТЫ МАТЕМАТИЧЕСКОЙ СТАТИСТИКИ</a></li>')
document.write('<li><a href="mathstat_2.html">11 ЭЛЕМЕНТЫ КОРРЕЛЯЦИОННОГО АНАЛИЗА</a></li>')
document.write('</ul></li>')
document.write('<li><a href="#">CPP</a><ul>')
document.write('<li><a href="cpp_1.html">1 C++ ITERATOR</a></li>')
document.write('<li><a href="cpp_2.html">2 C++ STRING</a></li>')
document.write('<li><a href="cpp_3.html">3 C++ VECTOR</a></li>')
document.write('<li><a href="cpp_4.html">4 C++ LIST</a></li>')
document.write('<li><a href="cpp_5.html">5 C++ STACK</a></li>')
document.write('<li><a href="cpp_6.html">6 C++ QUEUE</a></li>')
document.write('<li><a href="cpp_7.html">7 C++ DEQUE</a></li>')
document.write('<li><a href="cpp_8.html">8 C++ SET MULTISET</a></li>')
document.write('<li><a href="cpp_9.html">9 C++ MAP MULTIMAP</a></li>')
document.write('<li><a href="cpp_10.html">10 C++ ALGORITHM | LAMBDA</a></li>')
document.write('<li><a href="cpp_11.html">11 C++ WSTRING | RUS</a></li>')
document.write('<li><a href="cpp_12.html">12 C++ BINARY FILES</a></li>')
document.write('</ul></li>')
document.write('</ul></nav></header>')
document.write('<script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>')